# Generated by Django 5.2.6 on 2025-09-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_variation_created_at_variation_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
