# Generated by Django 5.2.6 on 2025-09-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_variation_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'ordering': ['variation_category']},
        ),
    ]
