# Generated by Django 5.2.6 on 2025-09-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pin_code',
            field=models.CharField(default=21, max_length=20),
            preserve_default=False,
        ),
    ]
